# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 15:18
from __future__ import unicode_literals

import apps.main.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flatblocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', apps.main.models.fields.CustomFileField(upload_to='block_image/%Y/%m/%d', verbose_name='Изображение')),
                ('modifier', models.CharField(choices=[('_full', '100%'), ('_third', '75%'), ('_half', '50%'), ('_fourth', '25%')], default='_full', max_length=50, verbose_name='Ориентация')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flatblocks.FlatBlock', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
