# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 11:29
from __future__ import unicode_literals

import apps.main.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlatBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text='A unique name used for reference in the templates', max_length=255, unique=True, verbose_name='Slug')),
                ('header', models.CharField(blank=True, help_text='An optional header for this content', max_length=255, verbose_name='Header')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('show_header', models.BooleanField(default=False, verbose_name='Показывать заголовок')),
                ('show_content', models.BooleanField(default=False, verbose_name='Показывать содержание')),
                ('show_file', models.BooleanField(default=False, verbose_name='Показывать файл')),
                ('show_url', models.BooleanField(default=False, verbose_name='Показывать URL')),
                ('set_linebreaks', models.BooleanField(default=True, verbose_name='Заменять перенос строки на тег <br />')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Url')),
                ('file', apps.main.models.fields.CustomFileField(blank=True, max_length=255, null=True, upload_to='flatblocks/%Y/%m/%d', verbose_name='Файл')),
                ('use_for_migrations', models.BooleanField(default=False, verbose_name='Включать в выгрузку миграции')),
            ],
            options={
                'verbose_name_plural': 'Flat blocks',
                'verbose_name': 'Flat block',
            },
        ),
    ]
